# ══════════════════════════════════════════════════════════════════════════════
# WINDOW BORDER
# ══════════════════════════════════════════════════════════════════════════════

window.active.border.color: #76946a
window.inactive.border.color: #68697a


# ══════════════════════════════════════════════════════════════════════════════
# TOGGLEKEYBINDS STATUS INDICATOR
# ══════════════════════════════════════════════════════════════════════════════

window.active.indicator.toggled-keybind.color: #c34043


# ══════════════════════════════════════════════════════════════════════════════
# WINDOW TITLEBAR BACKGROUND
# ══════════════════════════════════════════════════════════════════════════════

window.active.title.bg.color: #1f1f28
window.inactive.title.bg.color: #1f1f28

window.active.label.text.color: #c8c093
window.inactive.label.text.color: #717c7c
window.label.text.justify: center


# ══════════════════════════════════════════════════════════════════════════════
# WINDOW BUTTON HOVER OVERLAY
# ══════════════════════════════════════════════════════════════════════════════

window.button.hover.bg.color: #333343


# ══════════════════════════════════════════════════════════════════════════════
# WINDOW BUTTONS
# ══════════════════════════════════════════════════════════════════════════════

window.active.button.unpressed.image.color: #c8c093
window.inactive.button.unpressed.image.color: #717c7c


# ══════════════════════════════════════════════════════════════════════════════
# MENU
# ══════════════════════════════════════════════════════════════════════════════

menu.border.color: #68697a
menu.items.bg.color: #1f1f28
menu.items.text.color: #c8c093
menu.items.active.bg.color: #76946a
menu.items.active.text.color: #1f1f28
menu.separator.color: #68697a
menu.title.bg.color: #1f1f28
menu.title.text.color: #c8c093


# ══════════════════════════════════════════════════════════════════════════════
# ON SCREEN DISPLAY (WINDOW-CYCLE DIALOG)
# ══════════════════════════════════════════════════════════════════════════════

osd.bg.color: #1f1f28
osd.border.color: #76946a
osd.label.text.color: #c8c093
osd.window-switcher.preview.border.color: #68697a


# ══════════════════════════════════════════════════════════════════════════════
# META BUTTONS
# ══════════════════════════════════════════════════════════════════════════════

_meta.btn.close: #c34043
_meta.btn.min: #c0a36e
_meta.btn.max: #76946a
_meta.btn.inactive: #1f1f28
_meta.btn.error_hover: #c34043
