RDP_USER="icy"
RDP_PASS="1771"

RDP_IP="127.0.0.1"
RDP_PORT="3389"
WAFLAVOR="docker"

FREERDP_COMMAND="xfreerdp"

RDP_SCALE="100"
REMOVABLE_MEDIA="/run/media"
RDP_FLAGS="/cert:tofu /sound /microphone +home-drive"

AUTOPAUSE="on"
AUTOPAUSE_TIME="300"
