# Configuration file for mpv, a free and open-source media player.

# --------------------------------------
# ==== PERFORMANCE CONFIGURATION FOR MPV ====
# --------------------------------------

profile=high-quality

# --------------------------------------
# ==== ANIME SHADERS CONFIGURATION FOR MPV ====
# --------------------------------------

# Optimized shaders for lower-end GPU: Mode A (Fast)
glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"

# --------------------------------------
# ==== GENERAL MPV CONFIGURATION ====
# --------------------------------------

# Don't show the title bar
title-bar=no
# Don't show the on-screen controller (OSC) for a cleaner viewing experience, especially on lower-end hardware where it can cause performance issues
osc=no
# Automatically fit the video to 50% of the screen size
autofit=95%
# The last position of your video is saved when quitting mpv
save-position-on-quit=yes
# Default volume of the player
volume=100
# Forces showing subtitles while seeking through the video
demuxer-mkv-subtitle-preroll=yes
# Dithering method. 'auto' is usually the best choice, but you can experiment with other options if you have a high-end GPU and want to improve image quality at the cost of performance.
dither-depth=auto

# --------------------------------------
# ==== SCALING CONFIGURATION ====
# --------------------------------------

scale=spline36
dscale=mitchell
cscale=mitchell

# --------------------------------------
# ==== DEBAND CONFIGURATION ====
# --------------------------------------

# Deband parameters configuration. For Anime, 2:35:20:5 recommended for general use. Use 3:45:25:15 for older DVD, badly mastered BD or WEB streams. Use 4:60:30:30 for really, really bad streams.
# deband=2:35:20:5 # Default values are 1:64:16:48
# deband-iterations=1 # Range 1-16. Higher = better quality but more GPU usage. >5 is redundant.
# deband-threshold=35 # Range 0-4096. Deband strength.
# deband-range=20 # Range 1-64. Range of deband. Too high may destroy details.
# deband-grain=5 # Range 0-4096. Inject grain to cover up bad banding, higher value needed for poor sources.
# Note: For older/weaker iGPUs, instead of increasing deband-iterations you may need to increase deband-threshold instead if you need a stronger effect. I recommend 1:60:25:30 if you absolutely must run 1 iteration (lower quality but much less GPU usage).

# --------------------------------------
# ==== SCREENSHOT CONFIGURATION ====
# --------------------------------------

# Output format of screenshots
screenshot-format=png
# Same output bitdepth as the video
screenshot-high-bit-depth=yes # Set it "no" if you want to save disc space
# Compression of the PNG picture (1-9)
screenshot-png-compression=1 # Higher value means better compression, but takes more time
# Output directory
screenshot-dir="/home/icy/Pictures/Screenshots"

# --------------------------------------
# ==== SOME OTHER CONFIGURATIONS ====
# --------------------------------------

# Not too useful on modern hardware. 'auto-copy-safe' is a safe option to use if one wants to enable it. Defaults to 'no'.
# hwdec=auto-safe
# Video driver to use. The latest gpu-next is recommended.
vo=gpu-next
# DirectX on Windows (recommended if issues on Vulkan on Windows)
gpu-api=vulkan
# Don't close the player when the video ends, instead show the last frame. This is useful for anime where the ending credits are often still part of the video and you may want to watch them without having to reopen the video.
keep-open=yes

# For #3 settings (Material OSC)
# video-sync=display-resample
# force-windows=yes

autocreate-playlist=filter
image-display-duration=inf
