# ══════════════════════════════════════════════════════
# Window Rules
# ══════════════════════════════════════════════════════

# ─── Global ───
[[window_rule]]
blur = true
blur_optimized = false
opacity = 0.9

# ─── Noctalia / Umbriel ───
[[window_rule]]
match.app_id = "^dev.noctalia.Noctalia$"
default_floating = true
default_floating_size = { width = 0.5, height = 0.7 }

[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = true
default_floating_size = { width = 0.4, height = 0.5 }
default_position = { x = 32, y = 32, anchor = "center" }

[[window_rule]]
match.app_id = "^xdg-desktop-portal-gtk$"
default_floating = true
default_floating_size = { width = 0.4, height = 0.5 }
default_position = { x = 0, y = 0, anchor = "center" }

# ─── Picture-in-Picture ───
[[window_rule]]
match.title = "^(Picture-in-Picture|Picture in picture)$"
default_floating = true
default_floating_size = { width = 0.25, height = 0.25 }
default_output = "HDMI-A-1"
opacity = 1.0
default_position = { x = 10, y = 10, anchor = "bottom_right" }
default_focused = false
default_pinned = true

# ─── Yazi ───
[[window_rule]]
match.app_id = "^yazi\\.filemanager$"
default_floating = true
default_floating_size = { width = 0.55, height = 0.55 }
default_position = { x = 0, y = 0, anchor = "center" }

# ─── General Floating ───
[[window_rule]]
match.app_id = "^(dev\\.lemmy\\.swash|Mullvad Browser|Tor Browser|org\\.kde\\.kdeconnect\\.handler|org\\.kde\\.kdeconnect\\.daemon|com\\.rafaelmardojai\\.Blanket)$"
default_floating = true

# ─── Custom Floating & Sized ───
[[window_rule]]
match.app_id = "^org.localsend.localsend_app$"
default_floating = true
default_floating_size = { width = 0.4, height = 0.5 }

[[window_rule]]
match.app_id = "^com\\.obsproject\\.Studio$"
default_floating = true
default_floating_size = { width = 0.55, height = 0.65 }

[[window_rule]]
match.app_id = "^scrcpy$"
opacity = 1.0
default_floating = true
default_floating_size = { width = 0.3, height = 0.9 }

[[window_rule]]
match.app_id = "^nwg-look$"
default_floating = true
default_floating_size = { width = 0.4, height = 0.4 }

[[window_rule]]
match.app_id = "^wlfreerdp$"
opacity = 1.0

# ─── Opaque Floating ───
[[window_rule]]
match.app_id = "^(com\\.interversehq\\.qView|mpv)$"
opacity = 1.0
default_floating = true

# ─── Open Maximized ───
[[window_rule]]
match.app_id = "^(org\\.qutebrowser\\.qutebrowser|equibop||chrome-web\\.whatsapp\\.com__-Default|org\\.telegram\\.desktop|dev\\.zed\\.Zed)$"
default_maximize = true
